//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDP2VISIO {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Options : global::System.Configuration.ApplicationSettingsBase {
        
        private static Options defaultInstance = ((Options)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Options())));
        
        public static Options Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayConnected {
            get {
                return ((bool)(this["DisplayConnected"]));
            }
            set {
                this["DisplayConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MessagewhenVisioDocCompleted {
            get {
                return ((bool)(this["MessagewhenVisioDocCompleted"]));
            }
            set {
                this["MessagewhenVisioDocCompleted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MRUProtocol {
            get {
                return ((string)(this["MRUProtocol"]));
            }
            set {
                this["MRUProtocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MRUJumpServer {
            get {
                return ((string)(this["MRUJumpServer"]));
            }
            set {
                this["MRUJumpServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DocSize {
            get {
                return ((string)(this["DocSize"]));
            }
            set {
                this["DocSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GraphAlg {
            get {
                return ((string)(this["GraphAlg"]));
            }
            set {
                this["GraphAlg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CDP2Visio\\Stencils\\")]
        public string VisioStencilsPath {
            get {
                return ((string)(this["VisioStencilsPath"]));
            }
            set {
                this["VisioStencilsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("stencils.xml")]
        public string StencilsDBName {
            get {
                return ((string)(this["StencilsDBName"]));
            }
            set {
                this["StencilsDBName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection MRUDeviceList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MRUDeviceList"]));
            }
            set {
                this["MRUDeviceList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CDP2Visio\\Templates\\")]
        public string VisioTemplatesPath {
            get {
                return ((string)(this["VisioTemplatesPath"]));
            }
            set {
                this["VisioTemplatesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VisioA4Template {
            get {
                return ((string)(this["VisioA4Template"]));
            }
            set {
                this["VisioA4Template"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VisioA3Template {
            get {
                return ((string)(this["VisioA3Template"]));
            }
            set {
                this["VisioA3Template"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VisioA2Template {
            get {
                return ((string)(this["VisioA2Template"]));
            }
            set {
                this["VisioA2Template"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MRUOutputPath {
            get {
                return ((string)(this["MRUOutputPath"]));
            }
            set {
                this["MRUOutputPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MRUConnType {
            get {
                return ((string)(this["MRUConnType"]));
            }
            set {
                this["MRUConnType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CDP2Visio\\Inventory\\")]
        public string InventoryDBDirectory {
            get {
                return ((string)(this["InventoryDBDirectory"]));
            }
            set {
                this["InventoryDBDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MRUActiveDiscovery {
            get {
                return ((bool)(this["MRUActiveDiscovery"]));
            }
            set {
                this["MRUActiveDiscovery"] = value;
            }
        }
    }
}
